import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const site = await prisma.site.create({
    data: {
      name: "Demo Site",
      pages: {
        create: [
          {
            title: "Home",
            blocks: [
              {
                type: "Hero",
                props: {
                  headline: "Welcome to Your AI Site Builder!",
                  subheadline: "This page was auto-generated by your seed script."
                }
              },
              {
                type: "RichText",
                props: {
                  content: "You can now use the AI assistant to add, edit, or remove blocks instantly."
                }
              }
            ]
          }
        ]
      }
    },
    include: { pages: true }
  });

  console.log("✅ Seeded:", {
    siteId: site.id,
    pageId: site.pages[0].id
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
